[package]
name = "dotenvyaml-pyo3"
version = "0.2.0"
edition = "2021"
description = "PyO3 bindings for dotenvyaml"

[lib]
name = "dotenvyaml_rust"
crate-type = ["cdylib"]

[dependencies]
dotenvyaml-core = { path = "../core" }
pyo3 = { version = "0.23", features = ["extension-module"] }
serde_yaml = "0.9"